site_name: Connect Python OpenAPI Client
site_url: https://github.com/cloudblue/connect-python-openapi-client
repo_name: cloudblue/connect-python-openapi-client
repo_url: https://github.com/cloudblue/connect-python-openapi-client
edit_uri: ""
copyright: Copyright &copy; 2022 Ingram Micro. All Rights Reserved.
extra:
  generator: false
extra_css:
  - css/custom.css
theme:
  name: 'material'
  logo: logo_full.png
  favicon: favicon.ico
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

nav:
    - Home: index.md
    - User guide: guide.md
    - Testing tools: testing.md
