name: Build Docs For Connect Python OpenAPI Client

on:
  push:
    tags:
        - '*'

jobs:
  mddocs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup branch for markdown documentation
      run: |
        git remote add docs https://$GITHUB_TOKEN@github.com/cloudblue/connect-python-openapi-client.git
        sh -c 'test -n "$(git ls-remote docs docs/markdown)" && git push -d docs docs/markdown || exit 0'
        git checkout -B docs/markdown
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Build markdown docs
      run: |
        cd docs
        poetry run sphinx-build -M markdown ./ _build
        poetry run python genindex.py
    - name: Commit generated documentation
      run: |
        git config --local user.name "Github actions docs bot"
        git config --local user.email "bot@github.com"
        git add -f docs/_build/markdown
        git commit -am 'Docs generated'
    - name: Push markdown documentation branch to remote
      run: |
        git push -u docs docs/markdown
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
